---
- name: Configure jumphost for User
  hosts: jumphost
  become: True
  tags:
    - jumphost

  roles:

  - name: configure jumphost for user
    role: jumphost_user
    jumphost_user: "{{ demo_user }}"
    tags:
      - jumphost


