---
- name: Provision Docker Containers
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    container_count: 2

  tasks:

  - name: "Deploy {{ container_count }} container(s)"
    docker_container:
      docker_host: "{{ docker_host }}"
      name: "{{ ansible_user_id }}-{{ item }}"
      state: absent
    with_sequence: count={{ container_count }}
