---
- name: Provision Docker Containers
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    container_count: 2

  tasks:

  - name: Display docker image facts
    docker_image_facts:
      docker_host: "{{ docker_host }}"
      name: "{{ docker_image }}"
    register: docker_image_facts

  - name: debug display of docker_image_facts
    debug:
      var: docker_image_facts

  - name: "Deploy {{ container_count }} container(s)"
    docker_container:
      docker_host: "{{ docker_host }}"
      name: "{{ ansible_user_id }}-{{ item }}"
      labels: { owner: "{{ ansible_user_id }}" }
      image: "{{ docker_image }}"
      ports:
        - 22
      env:
        SSH_USER: "{{ ansible_user }}"
        SSH_USER_PASSWORD: "{{ ansible_ssh_pass }}"
    with_sequence: count={{ container_count }}
