---

- name: decode base64
  set_fact:
    jumphost_user_decode: "{{ demo_user | b64decode }}"

- name: debug jumphost_user_decode
  debug:
    var: jumphost_user_decode

- name: split username and password
  set_fact:
    jumphost_username: "{{ jumphost_user_decode.split(':')[0] }}"
    jumphost_user_password: "{{ jumphost_user_decode.split(':')[1] }}"

- name: create user
  user:
    name: "{{ jumphost_username }}"
    password: "{{ jumphost_user_password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
  register: create_user

- name: set public key fact
  set_fact:
    user_ssh_public_key: "{{ create_user.ssh_public_key }}"

- name: set authorized_keys
  authorized_key:
    user: "{{ jumphost_username }}"
    state: present
    key: "{{ user_ssh_public_key }}"

- name: create ppk
  command: "puttygen id_rsa -o {{ jumphost_username }}.ppk"
  args:
    chdir: "/home/{{ jumphost_username }}/.ssh"
    creates: "/home/{{ jumphost_username }}/.ssh/{{ jumphost_username }}.ppk"

- name: copy key
  copy:
    src: "/home/{{ jumphost_username }}/.ssh/{{ jumphost_username }}.ppk"
    dest: "/var/www/html/{{ jumphost_username }}.ppk"
    remote_src: yes

- name: Configure sudo access
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ jumphost_username }}"
    line: "{{ jumphost_username }}\t{{ jumphost_user_sudo_entry }}"
    backup: yes
  when:
    - jumphost_user_sudo is defined
    - jumphost_user_sudo
    - jumphost_user_sudo_entry is defined
  register: jumphost_sudo

- name: create bash history
  template:
    src: bash_history.j2
    dest: "/home/{{ jumphost_username }}/.bash_history"
    owner: "{{ jumphost_username }}"
    group: "{{ jumphost_username }}"
    mode: 0600

- name: create bash profile
  template:
    src: bash_profile.j2
    dest: "/home/{{ jumphost_username }}/.bash_profile"
    owner: "{{ jumphost_username }}"
    group: "{{ jumphost_username }}"
    mode: 0644

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ jumphost_username }}/{{ item }}"
    owner: "{{ jumphost_username }}"
    group: "{{ jumphost_username }}"
    mode: 0644
  with_items: "{{ jumphost_user_copy_files }}"



